# Laboratoire no 2 - Transition avec des états absorbants


Écrivez les noms des personnes de votre équipe et exécutez le prochain bloc de commandes qui charge les bibliothèques nécessaires pour ce laboratoire.

In [3]:
from numpy import matrix
from numpy import linalg
import random
random.seed(52)

nom1= "Andy Rayan Tchoupou Diffo"
nom2= "Cristobal Zuniga Solis"

print("Ce travail est fait par",nom1)
if nom2 != " " :
    print("et", nom2,".")


Ce travail est fait par Andy Rayan Tchoupou Diffo
et Cristobal Zuniga Solis .


# Problème de la marche de l'ivrogne

Commençons avec le problème de la **marche de l'ivrogne**.
Pour se rendre chez lui, un ivrogne doit parcourir 5 mètres sur un trottoir large de 2 mètres. À gauche du trottoir il y a un mur et à droite du trottoir il y a la rue. Si l'ivrogne est sur le côté gauche du trottoir, il y une chance sur deux d'avancer et de rester sur le côté gauche et une chance sur deux d'avancer et de se rendre sur le côté droit. S'il est sur le côté droit du trottoir, il a une chance sur trois d'avancer et d'aller sur le côté gauche, une chance sur trois d'avancer et de rester sur le côté droit et une chance sur trois de tomber dans la rue et de s'endromir.

S'il part du côté gauche du trottoir, quelle est la probabilité qu'il avance de 5 mètres sans tomber dans la rue ?

Posons:
- État 1: Coté gauche du trottoir,
- État 2: Côté droit du trottoir et
- État 3: La rue.

Voici la matrice de transition.
$$T=\begin{bmatrix}\frac{1}{2}&\frac{1}{3}&0\\\frac{1}{2}&\frac{1}{3}&0\\0&\frac{1}{3}&1\end{bmatrix}$$
Commençons par 100 simulations.

In [2]:
n = 100 # n nb de simulations
affiche=":"
num=0
for i in range(n):
    trajet="G"
    for j in range(5):
        alea=random.random()
        if trajet[-1]=="G":
            if alea<=1/2:
                trajet=trajet+"G"
            else:
                trajet=trajet+"D"
        elif trajet[-1]=="D":
            if alea<=1/3:
                trajet=trajet+"G"
            elif alea<=2/3:
                trajet=trajet+"D"
            else:
                trajet=trajet+"R"
    affiche=affiche+trajet+":"
    if trajet[-1]=="G" or trajet[-1]=="D":
        num = num +1
print(affiche)
ratio = num/n
    
print ("Dans les simulations, l'ivrogne est resté sur le trottoir:",100*ratio,"% des fois.")

:GDGDDR:GGDGDD:GGGDGG:GGGGGG:GDDR:GDDR:GGDDGG:GGDR:GGGDDD:GGGGGD:GGDDDR:GDGDR:GGDR:GDR:GGDGDR:GGGGDG:GDDDR:GGGDR:GDR:GDGDGD:GDR:GDGGGG:GGDGGD:GGDR:GDR:GDR:GGDR:GDGDR:GGGGGD:GDGDR:GGDR:GDR:GDGGDR:GGGDDG:GDGGGG:GDR:GGDR:GGDGGD:GDR:GDGDDR:GGDR:GGGGGD:GDDDDG:GDDGGG:GDGGDG:GDGGGG:GDGDR:GDR:GDGGDD:GDR:GGDDGG:GDGGDR:GDDGDD:GGDGGD:GDGGDR:GDDR:GGGDDD:GGGGGG:GDDGDD:GGGDR:GGDDDG:GGGGGD:GDDGGG:GGGDR:GDR:GDGDDR:GDDDGD:GGDGDR:GGGGDG:GDR:GGDR:GGGDGG:GDDGDR:GGDR:GDR:GGGDDD:GGGGGG:GDDR:GDGDGD:GGGGDR:GGGGGG:GGDR:GDDDGD:GGGDGG:GGGDR:GDGDGG:GDDR:GGGDR:GDR:GGDDDG:GDR:GDDGGD:GDR:GGGDR:GDR:GDGDR:GDGDGG:GDGDGD:GGDR:GDR:
Dans les simulations, l'ivrogne est resté sur le trottoir: 43.0 % des fois.


Voici un code qui calcule la probabilité à partir d'une matrice de transition.
$$P^{(5)}=T^5P^{(0)}$$

In [13]:
n= 5 #n est la longueur de la marche
P=matrix([[1],
          [0],
          [0]])
T=matrix([[1/2,1/3,0],
          [1/2,1/3,0],
          [0,1/3,1]])
P=T**n*P
print(P)    
print(P.item(0,0)+P.item(1,0))



[[0.24112654]
 [0.24112654]
 [0.51774691]]
0.482253086419753


**Conclusion**
L'ivrogne a une probabilité de rester sur le trottoir de 57,87%.

## À votre tour
Refaites le problème de l'ivrogne si le troittoir est large de 4 mètres et qu'il doit parcourir 10 mètres sans tomber dans la rue. S'il est à gauche, il a une chance sur deux d'avancer et de rester à gauche sinon il avance en se tassant d'un mètre à droite. Pour les deux positions au centre du trottoir, il a une chance sur trois d'avancer en se tassant d'un mètre à gauche, une chance sur trois d'avancer et de rester à la même position et une chance sur trois d'avancer en se tassant d'un mètre à droite. Pour la position la plus à droite, il a une chance sur trois d'avancer en se tassant d'un mètre à gauche, une chance sur trois d'avancer et de rester à la même position et une chance sur trois de tomber dans la rue.

Définissez vos états ici.

In [16]:
# Écrivez vos calculs ici.

n = 10 # Longueur de la marche

P1 = matrix([[1],
             [0],
             [0],
             [0],
             [0]]) 

T1 = matrix([[1/2, 1/3, 0  , 0  , 0  ],
             [1/2, 1/3, 1/3, 0  , 0  ],
             [0  , 1/3, 1/3, 1/3, 0  ],
             [0  , 0  , 1/3, 1/3, 0  ],
             [0  , 0  , 0  , 1/3, 1  ]])

P = T1 ** n * P1
print(P)   
print(P.item(0,0)+P.item(1,0)+P.item(2,0)+P.item(3,0))

[[0.19968518]
 [0.26896827]
 [0.19975111]
 [0.10552352]
 [0.22607191]]
0.7739280883249504


**Conclusion**
L'ivrogne a une probabilité de rester sur le trottoir de 77,37%.

Quelle est la longueur maximale qu'un ivrogne peut parcourir sur un trottoir de 4 mètres de large en partant à gauche et d'avoir moins de 90% de tomber dans la rue ?

Je m'attends à de l'essai-erreur pour trouver la réponse.

In [43]:
P10 = T1 ** 10 * P1
P10prob = P10.item(4,0)
print(P10prob)

P30 = T1 ** 30 * P1
P30prob = P30.item(4,0)
print(P30prob)

P45 = T1 ** 45 * P1
P45prob = P45.item(4,0)
print(P45prob)

P55 = T1 ** 55 * P1
P55prob = P55.item(4,0)
print(P55prob)

P52 = T1 ** 52 * P1
P52prob = P52.item(4,0)
print(P52prob)

0.22607191167504948
0.7019267084044223
0.8547066285884134
0.9100100349992405
0.8961014232191427


# Pile ou Face.

Deux personnes A et B jouent à un jeu. A lance une pièce, si c'est Face A gagne, sinon A donne la pièce à B qui tire à son tour. Si c'est pile, B gagne, sinon B redonne la pièce à A et ça recommence. Ce jeu ne semble pas équitable, car A commence.

Commençons par 100 simulations. Exécutez le code suivant.

In [8]:
n = 100 #nb de simulations
gain=[0,0]
for i in range(n):
    fin = False
    joueur=0
    while not(fin):
        tir=random.randrange(2)
        if tir==joueur:
            gain[tir]+=1
            fin=True
        joueur=1-joueur
print("Le joueur A a gagné",gain[0]," fois et le joueur B a gagné",gain[1], "fois.")


Le joueur A a gagné 70  fois et le joueur B a gagné 30 fois.


On peut décrire le jeu avec 4 états: 
- État 1: A joue
- État 2: B joue
- État 3: A gagne
- État 4: B gagne.

Voici la matrice de transition de cette situation.
$$T=\begin{bmatrix}0&\frac{1}{2}&0&0\\\frac{1}{2}&0&0&0\\\frac{1}{2}&0&1&0\\0&\frac{1}{2}&0&1\end{bmatrix}$$
La méthode vue en classe ne fonctionne pas, car ce n'est pas un état stationnaire qu'on cherche.
Le but est de déterminer la probabilité de gagner des deux joueurs.
Posons:
- $x_1$ la probabilité que A gagne si on est à l'état 1 et
- $x_2$ la probabilité que A gagne si on est à l'état 2.

Essayons de construire un système à deux équations et deux inconnus pour trouver la solution.

Si on est à l'état 1, on peut aller à l'état 3 (A gagne) avec une probabilité 1/2 ou aller à l'état 2 avec une probabilité de 1/2 et A gagne avec une probabilité de $x_2$. 

Donc la probabilité que A gagne à partir de l'état 1 ($x_1$) est 1/2 (si A tire Face) + (1/2)$(x_2)$ (si A tire Pile). Bref:
$$x_1=\frac{1}{2}+\frac{1}{2}x_2$$
De même, la probabilité que A gagne à partir de l'état 2 ($x_2$) est $\frac{1}{2}\times 0$ (si B tire pile) + (1/2)$(x_1)$ (si B tire Face). Bref:
$$x_2=\frac{1}{2}x_1$$

Si on traduit en système d'équations linéaires, on a:
$$\left \{
\begin{array}{c @{} c}
    x_1& - & \frac{1}{2}x_2 & = &\frac{1}{2} \\
    \frac{1}{2}x_1 &- & x_2 & = &0
\end{array}
\right.$$

Exécutez le prochain bloc de commandes qui va résoudre ce système d'équations par la matrice inverse.

In [31]:
#A est la matrice des coefficients
A= matrix([[1,-1/2],
           [1/2,-1]]) 
#B est la martrice des constantes
B= matrix([[1/2],
           [0]])
X=A**(-1)*B
print(X)

[[0.66666667]
 [0.33333333]]


### Conclusion
Comme on commençait à l'état 1 (le joueur A commence à tirer), la probabilité que le joueur A gagne est 2/3.

# À votre tour
Voici une nouvelle situation. Il y a deux joueurs: A et B. On tire à pile ou face jusqu'à temps qu'un joueur gagne. A gagne si on a tiré a deux faces consécutivement, B gagne si on a tiré 3 piles consécutivement. Vous devez calculer la probabilité que A gagne.

Écrivez vos états ici.
*Indice: Vous avez besoin d'au moins 5 états.*

In [32]:
#Écrivez votre matrice de transition ici.

Définissez vos variables et écrivez vos équations ici.

In [ ]:
#Écrivez vos calculs ici pour résoudre votre système d'équations ici.

Écrivez votre réponse ici.